package Presentacion;


import Entidad.ClsEntidadCargaAcedemica;
import Entidad.ClsEntidadCurso;
import Entidad.ClsEntidadDocente;
import Entidad.ClsEntidadPlanEstudio;
import Entidad.ClsEntidadSemestre;
import Negocio.ClsNegocioCargaAcademica;
import Negocio.ClsNegocioCurso;
import Negocio.ClsNegocioDocente;
import Negocio.ClsNegocioPlanEstudio;
import Negocio.ClsNegocioSemestre;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Asus
 */
public class FrmCRUDCargaAcademica extends javax.swing.JInternalFrame {

    public  ArrayList<ClsNegocioCargaAcademica> dato = null;
    SpinnerNumberModel  modelSpn = null;
    private TableRowSorter<TableModel> rowSorter;
    boolean esNuevo = true;
    
    ArrayList<String> idPlanEstudioBD = new ArrayList<>();
    ArrayList<String> idSemestreBD = new ArrayList<>();
    ArrayList<String> idDocenteBD = new ArrayList<>();
    
    public FrmCRUDCargaAcademica() {
        initComponents();
        cargarTabla();
        cargarComboPlanEstudio();
        cargarComboSemestre();
        cargarComboCurso();
        cargarComboDocente();
        txtIdCargaAcedemica.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdCargaAcedemica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCargaAcademica = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cmbPlanEstudio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbSemestre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtMatriculados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRetirados = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAbandono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbDocente = new javax.swing.JComboBox<>();
        cmbSeccion = new javax.swing.JComboBox<>();

        jLabel1.setText("ID :");

        jLabel2.setText("Plan de Estudio:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONTROL DE CARGA ACADEMICA");

        tblCargaAcademica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCargaAcademica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCargaAcademicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCargaAcademica);

        btnGuardar.setText("Nuevo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbPlanEstudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Semestre:");

        cmbSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Curso:");

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Matriculados:");

        jLabel7.setText("Retirados:");

        jLabel8.setText("Abandono:");

        jLabel9.setText("Docente:");

        jLabel10.setText("Sección:");

        cmbDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdCargaAcedemica)
                                .addComponent(cmbPlanEstudio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRetirados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAbandono, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(26, 26, 26)
                                    .addComponent(cmbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdCargaAcedemica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtRetirados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtAbandono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(cmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblCargaAcademicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargaAcademicaMouseClicked
        
        esNuevo = true;
        btnGuardar.setText("Nuevo");

        int fila = tblCargaAcademica.getSelectedRow();
        txtIdCargaAcedemica.setText(         (String) tblCargaAcademica.getValueAt(fila, 0));
        cmbPlanEstudio.setSelectedItem( String.valueOf(tblCargaAcademica.getValueAt(fila, 1)));
        cmbSemestre.setSelectedItem(    String.valueOf(tblCargaAcademica.getValueAt(fila, 2)));//SEMESTRE
        cmbCurso.setSelectedItem(       String.valueOf(tblCargaAcademica.getValueAt(fila, 3)));//CURSO
        cmbDocente.setSelectedItem(     String.valueOf(tblCargaAcademica.getValueAt(fila, 7)));//DOCENTE        
        cmbSeccion.setSelectedItem(     String.valueOf( tblCargaAcademica.getValueAt(fila, 8)));
        
        txtMatriculados.setText( (String) tblCargaAcademica.getValueAt(fila, 4) );//4
        txtRetirados.setText( (String) tblCargaAcademica.getValueAt(fila, 5) );//5
        txtAbandono.setText( (String) tblCargaAcademica.getValueAt(fila, 6) );//6
        
        activarBotones(true, true, true);
        activarTextos(true);
        
    }//GEN-LAST:event_tblCargaAcademicaMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        //IDS DE PLAN DE ESTUDIO
        String[] idsPE = new String[idPlanEstudioBD.size()];
        idsPE = idPlanEstudioBD.toArray(idsPE);
        
        //IDS DE SEMESTRE
        String[] idsSE = new String[idSemestreBD.size()];
        idsSE = idSemestreBD.toArray(idsSE);
        
        //IDS DE DOCENTES
        String[] idsDO = new String[idDocenteBD.size()];
        idsDO = idDocenteBD.toArray(idsDO);
        
        if (esNuevo) {
            activarTextos(true);
            activarBotones(true, false, false);
            limpiar();
            
            //
            txtMatriculados.setText("0");
            txtAbandono.setText("0");
            txtRetirados.setText("0");
            
            btnGuardar.setText("Guardar");
            esNuevo = false;
        } else {
            if (txtMatriculados.getText().equals("") || txtRetirados.getText().equals("") || txtAbandono.getText().equals("") ) {
                JOptionPane.showMessageDialog(null, "Complete el campo de Carga Academica antes de guardar");
            } else {
                ClsNegocioCargaAcademica negoCar = new ClsNegocioCargaAcademica();
                ClsEntidadCargaAcedemica entCar  = new ClsEntidadCargaAcedemica();
                
                entCar.setIdPlanEstudio(Integer.parseInt(idsPE[cmbPlanEstudio.getSelectedIndex()]));
                entCar.setIdSemestre(Integer.parseInt(idsSE[cmbSemestre.getSelectedIndex()]));
                entCar.setIdCurso(cmbCurso.getSelectedItem().toString());
                entCar.setAlumnosMatriculados(Integer.parseInt(txtMatriculados.getText()));
                entCar.setAlumnosRetirados(Integer.parseInt(txtRetirados.getText()));
                entCar.setAlumnosAbandono(Integer.parseInt(txtAbandono.getText()));
                entCar.setCodDocente(idsDO[cmbDocente.getSelectedIndex()]);
                entCar.setSeccion(cmbSeccion.getSelectedItem().toString());
                
                negoCar.AgregarCargaAcademica(entCar);

                limpiar();
                activarTextos(false);
                activarBotones(true, false, false);
                cargarTabla();
                btnGuardar.setText("Nuevo");
                esNuevo = true;
            }
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ClsNegocioCargaAcademica negoCar = new ClsNegocioCargaAcademica();
        if (!txtIdCargaAcedemica.getText().equals("")) {
            negoCar.EliminarCargaAcademica(txtIdCargaAcedemica.getText());
            cargarTabla();
            limpiar();
            activarTextos(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsNegocioCargaAcademica negoCar = new ClsNegocioCargaAcademica();
        ClsEntidadCargaAcedemica entCar  = new ClsEntidadCargaAcedemica();
        
        if (!txtIdCargaAcedemica.getText().equals("")) {
            
            //IDS DE PLAN DE ESTUDIO
            String[] idsPE = new String[idPlanEstudioBD.size()];
            idsPE = idPlanEstudioBD.toArray(idsPE);

            //IDS DE SEMESTRE
            String[] idsSE = new String[idSemestreBD.size()];
            idsSE = idSemestreBD.toArray(idsSE);

            //IDS DE DOCENTES
            String[] idsDO = new String[idDocenteBD.size()];
            idsDO = idDocenteBD.toArray(idsDO);

            entCar.setIdCargaAcademica(Integer.parseInt(txtIdCargaAcedemica.getText()));
            entCar.setIdPlanEstudio(Integer.parseInt(idsPE[cmbPlanEstudio.getSelectedIndex()]));
            entCar.setIdSemestre(Integer.parseInt(idsSE[cmbSemestre.getSelectedIndex()]));
            entCar.setIdCurso(cmbCurso.getSelectedItem().toString());
            entCar.setAlumnosMatriculados(Integer.parseInt(txtMatriculados.getText()));
            entCar.setAlumnosRetirados(Integer.parseInt(txtRetirados.getText()));
            entCar.setAlumnosAbandono(Integer.parseInt(txtAbandono.getText()));
            entCar.setCodDocente(idsDO[cmbDocente.getSelectedIndex()]);
            entCar.setSeccion(cmbSeccion.getSelectedItem().toString());
            
            negoCar.ModificarCargaAcademica(entCar);
            
            limpiar();
            activarTextos(false);
            cargarTabla();
            btnGuardar.setText("Nuevo");
            esNuevo = true;
            
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cargarTabla() {
        String columnas[] = {
            "ID", "Plan Estudio", "Semestre", "Curso", "Matriculados",
            "Retirados", "Abandono", "Docente", "Seccion"};
        ArrayList<ClsNegocioCargaAcademica> dato = null;
        try {
            ClsNegocioCargaAcademica datos = new ClsNegocioCargaAcademica();
            dato = datos.MostrarCargaAcademica();
            Iterator iterator = dato.iterator();
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            modeloTabla.setRowCount(0);
            String campo[] = new String[9];
            
            while (iterator.hasNext()) {
                ClsEntidadCargaAcedemica objenti = new ClsEntidadCargaAcedemica();

                objenti = (ClsEntidadCargaAcedemica) iterator.next();

                campo[0] = String.valueOf(objenti.getIdCargaAcademica());
                campo[1] = objenti.getNombrePlanEstudio();
                campo[2] = objenti.getNombreSemestre();
                campo[3] = objenti.getIdCurso();
                campo[4] = String.valueOf(objenti.getAlumnosMatriculados());
                campo[5] = String.valueOf(objenti.getAlumnosRetirados());
                campo[6] = String.valueOf(objenti.getAlumnosAbandono());
                campo[7] = objenti.getNombreDocente();
                campo[8] = objenti.getSeccion();
                
                modeloTabla.addRow(campo);
            }
            
            tblCargaAcademica.setModel(modeloTabla);
            modeloTabla.fireTableDataChanged();
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        }    
    }
    
    //CARGAR TODOS LOS PLANES DE ESTUDIOS EN EL COMBOBOX
    private void cargarComboPlanEstudio(){
        ArrayList<ClsNegocioPlanEstudio> datoPECB = null;
        
        try {
            ClsNegocioPlanEstudio datos = new ClsNegocioPlanEstudio();
            datoPECB = datos.MostrarPlanEstudios();
            Iterator iterator = datoPECB.iterator();
            
            DefaultComboBoxModel modelitoPE = new DefaultComboBoxModel();
            
            cmbPlanEstudio.removeAllItems();
            
            int con = 0;
            
            idPlanEstudioBD.clear();
            
            while (iterator.hasNext()) {
                ClsEntidadPlanEstudio objenti = new ClsEntidadPlanEstudio();

                objenti = (ClsEntidadPlanEstudio) iterator.next();

                idPlanEstudioBD.add(String.valueOf(objenti.getIdPlanEstudio()));
                
                modelitoPE.addElement(objenti.getNombrePlanEstudio());
                
                
            }
            
            cmbPlanEstudio.setModel(modelitoPE);
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        } 
    }
    
    //CARGAR TODOS LOS SEMESTRES EN EL COMBOBOX
    private void cargarComboSemestre(){
        ArrayList<ClsNegocioSemestre> datoSMCB = null;
        try {
            ClsNegocioSemestre datos = new ClsNegocioSemestre();
            datoSMCB = datos.MostrarSemestres();
            Iterator iterator = datoSMCB.iterator();
            
            DefaultComboBoxModel modelitoSE = new DefaultComboBoxModel();
            
            cmbSemestre.removeAllItems();
            
            while (iterator.hasNext()) {
                ClsEntidadSemestre objenti = new ClsEntidadSemestre();

                objenti = (ClsEntidadSemestre) iterator.next();

                modelitoSE.addElement(objenti.getNombreSemestre());
                
                idSemestreBD.add(String.valueOf(objenti.getIdSemestre()));
                
            }
            cmbSemestre.setModel(modelitoSE);
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        }  
    }
    
    //CARGAR TODOS LOS CURSO EN EL COMBOBOX
    private void cargarComboCurso(){
        ArrayList<ClsNegocioCurso> datoCCB = null;
        try {
            
            ClsNegocioCurso  datos = new ClsNegocioCurso();
            
            datoCCB = datos.seleccionarTodasLosCursos();

            Iterator iterator = datoCCB.iterator();

            DefaultComboBoxModel modelitoC = new DefaultComboBoxModel();
            
            cmbCurso.removeAllItems();

            while (iterator.hasNext()) {
                ClsEntidadCurso objenti = new ClsEntidadCurso();

                objenti = (ClsEntidadCurso) iterator.next();

                modelitoC.addElement(objenti.getIdCurso());
                
            }
            cmbCurso.setModel(modelitoC);

            datos.conexion.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //CARGAR TODOS LOS DOCENTE EN EL COMBOBOX
    private void cargarComboDocente(){
        ArrayList<ClsNegocioDocente> datoDCB = null;
        try {
            ClsNegocioDocente datos = new ClsNegocioDocente();
            datoDCB = datos.MostrarDocentes();
            Iterator iterator = datoDCB.iterator();
            
            DefaultComboBoxModel modelitoDCB = new DefaultComboBoxModel();
            
            cmbDocente.removeAllItems();
            
            while (iterator.hasNext()) {
                ClsEntidadDocente objenti = new ClsEntidadDocente();

                objenti = (ClsEntidadDocente) iterator.next();

                modelitoDCB.addElement(objenti.getNombreDocente());
                
                idDocenteBD.add(String.valueOf(objenti.getCodDocente()));
                
            }
            
            cmbDocente.setModel(modelitoDCB);
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        }  
    }
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        rowSorter = new TableRowSorter<>(tblCargaAcademica.getModel());
        tblCargaAcademica.setRowSorter(rowSorter);
        String text = txtBuscar.getText();
        if (text.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void activarBotones(boolean nuevoEstado, boolean modificarEstado, boolean eliminarEstado) {
        btnGuardar.setEnabled(nuevoEstado);
        btnModificar.setEnabled(modificarEstado);
        btnEliminar.setEnabled(eliminarEstado);
    }
    
    private void activarTextos(boolean estado) {
        
    }
    
    private void limpiar() {
        txtIdCargaAcedemica.setText("");
        txtMatriculados.setText("");
        txtRetirados.setText("");
        txtAbandono.setText("");
        txtBuscar.setText("");
        cmbCurso.setSelectedIndex(0);
        cmbDocente.setSelectedIndex(0);
        cmbPlanEstudio.setSelectedIndex(0);
        cmbSeccion.setSelectedIndex(0);
        cmbSemestre.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbDocente;
    private javax.swing.JComboBox<String> cmbPlanEstudio;
    private javax.swing.JComboBox<String> cmbSeccion;
    private javax.swing.JComboBox<String> cmbSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCargaAcademica;
    private javax.swing.JTextField txtAbandono;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdCargaAcedemica;
    private javax.swing.JTextField txtMatriculados;
    private javax.swing.JTextField txtRetirados;
    // End of variables declaration//GEN-END:variables

}