/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsEntidadDocente;
import Negocio.ClsNegocioDocente;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Drei
 */
public class FrmCRUDDocente extends javax.swing.JInternalFrame {

    private TableRowSorter<TableModel> rowSorter;
    boolean esNuevo = true;
    
    public FrmCRUDDocente() {
        initComponents();
        cargarCodDocente();        
        txtCodDocente.setEnabled(false);
        activarTextos(false);
        cargarTabla();
        activarBotones(true, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodDocente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreDoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmailDoc = new javax.swing.JTextField();
        txtCelularDoc = new javax.swing.JTextField();
        txtGradoDoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocente = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        jLabel1.setText("Código :");

        jLabel2.setText("Nombre :");

        jLabel3.setText("Email :");

        jLabel4.setText("Celular :");

        jLabel5.setText("Grado :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONTROL DE DOCENTE");

        tblDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocente);

        btnGuardar.setText("Nuevo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCelularDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42)
                                .addComponent(txtGradoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmailDoc)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(txtNombreDoc)
                            .addComponent(txtCodDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBuscar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(313, 313, 313))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelularDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtGradoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (esNuevo) {
            activarTextos(true);
            activarBotones(true, false, false);
            limpiar();
            cargarCodDocente();
            btnGuardar.setText("Guardar");
            esNuevo = false;            
        } else {
            if (txtNombreDoc.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Complete el campo de nombre antes de guardar");
            } else {
                ClsNegocioDocente negoDoc = new ClsNegocioDocente();
                ClsEntidadDocente entDoc = new ClsEntidadDocente();
                entDoc.setCodDocente(txtCodDocente.getText());
                entDoc.setNombreDocente(txtNombreDoc.getText());
                entDoc.setEmailDocente(txtEmailDoc.getText());
                entDoc.setCelularDocente(txtCelularDoc.getText());
                entDoc.setGradoDocente(txtGradoDoc.getText());
                negoDoc.AgregarDocente(entDoc);
                limpiar();
                activarTextos(false);
                activarBotones(true, false, false);
                cargarCodDocente();
                cargarTabla();
                btnGuardar.setText("Nuevo");
                esNuevo = true;  
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        rowSorter = new TableRowSorter<>(tblDocente.getModel());
        tblDocente.setRowSorter(rowSorter);
        String text = txtBuscar.getText();
        if (text.trim().length() == 0) {
           rowSorter.setRowFilter(null);
        } else {
           rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocenteMouseClicked
        esNuevo = true;
        btnGuardar.setText("Nuevo");
        
        int fila = tblDocente.getSelectedRow();
        txtCodDocente.setText((String) tblDocente.getValueAt(fila, 0));
        txtNombreDoc.setText((String) tblDocente.getValueAt(fila, 1));
        txtEmailDoc.setText((String) tblDocente.getValueAt(fila, 2));
        txtCelularDoc.setText((String) tblDocente.getValueAt(fila, 3));
        txtGradoDoc.setText((String) tblDocente.getValueAt(fila, 4));
        activarBotones(true, true, true);
        activarTextos(true);
       
    }//GEN-LAST:event_tblDocenteMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ClsNegocioDocente negoDoc = new ClsNegocioDocente();
        negoDoc.EliminarDocente(txtCodDocente.getText());
        cargarTabla();
        limpiar();
        activarTextos(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsNegocioDocente negoDoc = new ClsNegocioDocente();
        ClsEntidadDocente entDoc = new ClsEntidadDocente();
        entDoc.setCodDocente(txtCodDocente.getText());
        entDoc.setNombreDocente(txtNombreDoc.getText());
        entDoc.setEmailDocente(txtEmailDoc.getText());
        entDoc.setCelularDocente(txtCelularDoc.getText());
        entDoc.setGradoDocente(txtGradoDoc.getText());
        negoDoc.ModificarDocente(entDoc);
        limpiar();
        activarTextos(false);
        cargarCodDocente();
        cargarTabla();
        btnGuardar.setText("Nuevo");
        esNuevo = true;  
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDocente;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCelularDoc;
    private javax.swing.JTextField txtCodDocente;
    private javax.swing.JTextField txtEmailDoc;
    private javax.swing.JTextField txtGradoDoc;
    private javax.swing.JTextField txtNombreDoc;
    // End of variables declaration//GEN-END:variables

    private void cargarCodDocente() {
        ClsNegocioDocente negoDoc = new ClsNegocioDocente();        
        txtCodDocente.setText(negoDoc.ObtenerCodigo());
        try {
            negoDoc.conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmCRUDDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void limpiar(){
        txtCelularDoc.setText("");
        txtCodDocente.setText("");
        txtEmailDoc.setText("");
        txtGradoDoc.setText("");
        txtNombreDoc.setText("");
//        txtBuscar.setText("");
//        cargarTabla();
        cargarCodDocente();
    }

    private void cargarTabla() {
        String columnas[] = {"Código","Nombre","Email","Celular","Grado"};
        ArrayList<ClsNegocioDocente> dato = null;
        try {
            ClsNegocioDocente datos = new ClsNegocioDocente();
            dato = datos.MostrarDocentes();
            Iterator iterator = dato.iterator();
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            modeloTabla.setRowCount(0);
            String campo[] = new String[5];
            
            while (iterator.hasNext()) {
                ClsEntidadDocente objenti = new ClsEntidadDocente();

                objenti = (ClsEntidadDocente) iterator.next();

                campo[0] = objenti.getCodDocente();
                campo[1] = objenti.getNombreDocente();
                campo[2] = objenti.getEmailDocente();
                campo[3] = objenti.getCelularDocente();
                campo[4] = objenti.getGradoDocente();
                modeloTabla.addRow(campo);
            }
            
            tblDocente.setModel(modeloTabla);
            modeloTabla.fireTableDataChanged();
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        }    
    }
    
    private void activarBotones(boolean nuevoEstado, boolean modificarEstado, boolean eliminarEstado){
        btnGuardar.setEnabled(nuevoEstado);
        btnModificar.setEnabled(modificarEstado);
        btnEliminar.setEnabled(eliminarEstado);
    }

    private void activarTextos(boolean estado) {
        txtNombreDoc.setEnabled(estado);
        txtGradoDoc.setEnabled(estado);
        txtEmailDoc.setEnabled(estado);
        txtCelularDoc.setEnabled(estado);
    }


}
