package Presentacion;

import Entidad.ClsEntidadPlanEstudio;
import Negocio.ClsNegocioPlanEstudio;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Asus
 */
public class FrmCRUDPlanEstudio extends javax.swing.JInternalFrame {

    private TableRowSorter<TableModel> rowSorter;
    boolean esNuevo = true;
    
    public FrmCRUDPlanEstudio() {
        initComponents();
        txtIdPlanEstudio.setEnabled(false);
        activarCajas(false);
        cargarTabla();
        activarBotones(true, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtIdPlanEstudio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombrePlanEstudio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanEstudio = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONTROL DE PLAN DE ESTUDIO");

        jLabel2.setText("Nombre :");

        tblPlanEstudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPlanEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlanEstudioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlanEstudio);

        btnGuardar.setText("Nuevo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBuscar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(313, 313, 313))))))
                        .addContainerGap(7, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombrePlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ClsNegocioPlanEstudio negoSem = new ClsNegocioPlanEstudio();
        negoSem.EliminarPlanEstudio(txtIdPlanEstudio.getText());
        cargarTabla();
        limpiarCajas();
        activarCajas(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsNegocioPlanEstudio negoSem = new ClsNegocioPlanEstudio();
        ClsEntidadPlanEstudio entSem = new ClsEntidadPlanEstudio();

        entSem.setIdPlanEstudio(Integer.parseInt(txtIdPlanEstudio.getText()));
        entSem.setNombrePlanEstudio(txtNombrePlanEstudio.getText());
        negoSem.ModificarPlanEstudio(entSem);
        limpiarCajas();
        activarCajas(false);
        cargarTabla();
        btnGuardar.setText("Nuevo");
        esNuevo = true;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        rowSorter = new TableRowSorter<>(tblPlanEstudio.getModel());
        tblPlanEstudio.setRowSorter(rowSorter);
        String text = txtBuscar.getText();
        if (text.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblPlanEstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlanEstudioMouseClicked
        esNuevo = true;
        btnGuardar.setText("Nuevo");

        int fila = tblPlanEstudio.getSelectedRow();
        txtIdPlanEstudio.setText((String) tblPlanEstudio.getValueAt(fila, 0));
        txtNombrePlanEstudio.setText((String) tblPlanEstudio.getValueAt(fila, 1));
        activarBotones(true, true, true);
        activarCajas(true);
    }//GEN-LAST:event_tblPlanEstudioMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (esNuevo) {
            activarCajas(true);
            activarBotones(true, false, false);
            limpiarCajas();
            btnGuardar.setText("Guardar");
            esNuevo = false;
        } else {
            if (txtNombrePlanEstudio.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Complete el campo de nombre antes de guardar");
            } else {
                ClsNegocioPlanEstudio negoPlanEstudio = new ClsNegocioPlanEstudio();
                ClsEntidadPlanEstudio entPlanEstudio = new ClsEntidadPlanEstudio();

                entPlanEstudio.setNombrePlanEstudio(txtNombrePlanEstudio.getText());
                negoPlanEstudio.AgregarPlanEstudio(entPlanEstudio);
                limpiarCajas();
                activarCajas(false);
                activarBotones(true, false, false);
                cargarTabla();
                btnGuardar.setText("Nuevo");
                esNuevo = true;
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    private void activarCajas(boolean estado) {
        txtNombrePlanEstudio.setEnabled(estado);
    }

    private void cargarTabla(){
        String columnas[] = {"ID","Nombre"};
        ArrayList<ClsNegocioPlanEstudio> dato = null;
        try {
            ClsNegocioPlanEstudio datos = new ClsNegocioPlanEstudio();
            dato = datos.MostrarPlanEstudios();
            Iterator iterator = dato.iterator();
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            modeloTabla.setRowCount(0);
            String campo[] = new String[2];
            
            while (iterator.hasNext()) {
                ClsEntidadPlanEstudio objenti = new ClsEntidadPlanEstudio();

                objenti = (ClsEntidadPlanEstudio) iterator.next();

                campo[0] = String.valueOf(objenti.getIdPlanEstudio());
                campo[1] = objenti.getNombrePlanEstudio();
                modeloTabla.addRow(campo);
            }
            
            tblPlanEstudio.setModel(modeloTabla);
            modeloTabla.fireTableDataChanged();
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        } 
    }
    
    private void activarBotones(boolean nuevoEstado, boolean modificarEstado, boolean eliminarEstado) {
        btnGuardar.setEnabled(nuevoEstado);
        btnModificar.setEnabled(modificarEstado);
        btnEliminar.setEnabled(eliminarEstado);
    }
    
    private void limpiarCajas(){
        txtIdPlanEstudio.setText("");
        txtNombrePlanEstudio.setText("");
        txtBuscar.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlanEstudio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdPlanEstudio;
    private javax.swing.JTextField txtNombrePlanEstudio;
    // End of variables declaration//GEN-END:variables
}
