/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsEntidadDocente;
import Entidad.ClsEntidadUsuario;
import Negocio.ClsNegocioDocente;
import Negocio.ClsNegocioUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Drei
 */
public class FrmCRUDUsuario extends javax.swing.JInternalFrame {

    private TableRowSorter<TableModel> rowSorter;
    private TableRowSorter<TableModel> rowSorter2;
    boolean esNuevo = true;
    
    public FrmCRUDUsuario() {
        initComponents();
        cargarTablaDocentes();
        cargarIdUsuario();
        txtIdUsu.setEnabled(false);
        txtCodDoc.setEnabled(false);
        activarTextos(false);
        cargarTablaUsuario();
        activarBotones(true, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdUsu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodDoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContraseniaUsu = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cmbNivelUsu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbEstadoUsu = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtBuscarUsu = new javax.swing.JTextField();
        btnBuscarUsu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("Código :");

        jPasswordField2.setText("jPasswordField1");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocente);

        jLabel1.setText("ID:");

        jLabel2.setText("Código :");

        jLabel3.setText("Contraseña :");

        txtContraseniaUsu.setText("123");
        txtContraseniaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaUsuActionPerformed(evt);
            }
        });

        jLabel5.setText("Nivel :");

        cmbNivelUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Supervisor", "Administrador" }));

        jLabel7.setText("Estado :");

        cmbEstadoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnGuardar.setText("Nuevo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscarUsu.setText("Buscar");
        btnBuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuActionPerformed(evt);
            }
        });

        jLabel8.setText("Seleccione un docente de la tabla :");

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUsuario);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CONTROL DE USUARIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(34, 34, 34))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel1))
                                            .addGap(44, 44, 44)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodDoc)
                                            .addComponent(cmbNivelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbEstadoUsu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtContraseniaUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnEliminar)
                                    .addComponent(btnModificar)
                                    .addComponent(btnLimpiar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBuscarUsu)
                                    .addComponent(txtBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtContraseniaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbNivelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cmbEstadoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        rowSorter = new TableRowSorter<>(tblDocente.getModel());
        tblDocente.setRowSorter(rowSorter);
        String text = txtBuscar.getText();
        if (text.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocenteMouseClicked
//        esNuevo = true;
//        btnGuardar.setText("Nuevo");
        if (!esNuevo) {
            int fila = tblDocente.getSelectedRow();
            txtCodDoc.setText((String) tblDocente.getValueAt(fila, 0));
        }
    }//GEN-LAST:event_tblDocenteMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (esNuevo) {
            activarTextos(true);
            activarBotones(true, false, false);
            limpiar();
            cargarIdUsuario();
            btnGuardar.setText("Guardar");
            esNuevo = false;
        } else {           
            ClsNegocioUsuario negoUsu = new ClsNegocioUsuario();
            ClsEntidadUsuario entUsu = new ClsEntidadUsuario();
            entUsu.setCodDocente(txtCodDoc.getText());
            entUsu.setContraseniaUsuario(String.valueOf(txtContraseniaUsu.getPassword()));
            entUsu.setNivelUsuario((String) cmbNivelUsu.getSelectedItem());
            entUsu.setEstadoUsuario((String) cmbEstadoUsu.getSelectedItem());
            negoUsu.AgregarUsuario(entUsu);
            limpiar();
            activarTextos(false);
            activarBotones(true, false, false);
            cargarIdUsuario();
            cargarTablaDocentes();
            cargarTablaUsuario();
            btnGuardar.setText("Nuevo");
            esNuevo = true;
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ClsNegocioUsuario negoUsu=  new ClsNegocioUsuario();
        negoUsu.EliminarUsuario(txtIdUsu.getText());
        cargarTablaDocentes();
        cargarTablaUsuario();
        limpiar();
        activarTextos(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsNegocioUsuario negoUsu = new ClsNegocioUsuario();
        ClsEntidadUsuario entUsu = new ClsEntidadUsuario();
        entUsu.setIdUsuario(txtIdUsu.getText());
        entUsu.setCodDocente(txtCodDoc.getText());
        entUsu.setContraseniaUsuario(String.valueOf(txtContraseniaUsu.getPassword()));
        entUsu.setNivelUsuario((String) cmbNivelUsu.getSelectedItem());
        entUsu.setEstadoUsuario((String) cmbEstadoUsu.getSelectedItem());
        negoUsu.ModificarUsuario(entUsu);
        limpiar();
        activarTextos(false);
        cargarIdUsuario();
        cargarTablaUsuario();
        btnGuardar.setText("Nuevo");
        esNuevo = true;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuActionPerformed
        rowSorter2 = new TableRowSorter<>(tblUsuario.getModel());
        tblUsuario.setRowSorter(rowSorter2);
        String text = txtBuscarUsu.getText();
        if (text.trim().length() == 0) {
            rowSorter2.setRowFilter(null);
        } else {
            rowSorter2.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_btnBuscarUsuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtContraseniaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaUsuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarUsu;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbEstadoUsu;
    private javax.swing.JComboBox<String> cmbNivelUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDocente;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarUsu;
    private javax.swing.JTextField txtCodDoc;
    private javax.swing.JPasswordField txtContraseniaUsu;
    private javax.swing.JTextField txtIdUsu;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaDocentes() {
        String columnas[] = {"Código","Nombre","Email","Celular","Grado"};
        ArrayList<ClsNegocioDocente> dato = null;
        try {
            ClsNegocioDocente datos = new ClsNegocioDocente();
            dato = datos.MostrarDocentesSinUsuario();
            Iterator iterator = dato.iterator();
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            modeloTabla.setRowCount(0);
            String campo[] = new String[5];
            
            while (iterator.hasNext()) {
                ClsEntidadDocente objenti = new ClsEntidadDocente();

                objenti = (ClsEntidadDocente) iterator.next();

                campo[0] = objenti.getCodDocente();
                campo[1] = objenti.getNombreDocente();
                campo[2] = objenti.getEmailDocente();
                campo[3] = objenti.getCelularDocente();
                campo[4] = objenti.getGradoDocente();
                modeloTabla.addRow(campo);
            }
            
            tblDocente.setModel(modeloTabla);
            modeloTabla.fireTableDataChanged();
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        } 
    }

    private void cargarIdUsuario() {
        ClsNegocioUsuario negoUsu = new ClsNegocioUsuario();        
        txtIdUsu.setText(negoUsu.ObtenerID());
        try {
            negoUsu.conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmCRUDDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void activarTextos(boolean estado) {
        txtContraseniaUsu.setEnabled(estado);
        cmbNivelUsu.setEnabled(estado);
        cmbEstadoUsu.setEnabled(estado);
    }

    private void cargarTablaUsuario() {
        String columnas[] = {"ID","Código","Nivel","Estado"};
        ArrayList<ClsNegocioUsuario> dato = null;
        try {
            ClsNegocioUsuario datos = new ClsNegocioUsuario();
            dato = datos.MostrarUsuarios();
            Iterator iterator = dato.iterator();
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            modeloTabla.setRowCount(0);
            String campo[] = new String[4];
            
            while (iterator.hasNext()) {
                ClsEntidadUsuario objenti = new ClsEntidadUsuario();

                objenti = (ClsEntidadUsuario) iterator.next();

                campo[0] = objenti.getIdUsuario();
                campo[1] = objenti.getCodDocente();
                campo[2] = objenti.getNivelUsuario();
                campo[3] = objenti.getEstadoUsuario();
                modeloTabla.addRow(campo);
            }
            
            tblUsuario.setModel(modeloTabla);
            modeloTabla.fireTableDataChanged();
            datos.conexion.close();

        } catch (Exception e) {
            e.printStackTrace();
        } 
    }

    private void activarBotones(boolean nuevoEstado, boolean modificarEstado, boolean eliminarEstado) {
        btnGuardar.setEnabled(nuevoEstado);
        btnModificar.setEnabled(modificarEstado);
        btnEliminar.setEnabled(eliminarEstado);
    }

    private void limpiar() {
        txtCodDoc.setText("");
        txtContraseniaUsu.setText("123");
        cmbEstadoUsu.setSelectedIndex(0);
        cmbNivelUsu.setSelectedIndex(0);
    }
}
